# FlatOut Online Play Support by Chloe @gaycoderprincess
# enjoy, nya~ :3

[main]
server_ip = "127.0.0.1"		# Server host's IP address
port_game = 23756		# Gameplay port, needs to be forwarded for the server host!
port_lobby = 23757		# Lobby broadcast port, needs to be forwarded for the server host!

[logging]
log_lobby_search = false	# Logs connection attempts when searching for lobbies